### ISSUE TITLE
rollup 原始代码时基于第几版的代码

### ISSUE THREAD

**Issue by xiaochengzi6** [woai3c/copy-rollup#2]
Hellow, 你提供的思路和注释非常不错，我这几天也在通过本仓库学习 rollup 的源码，但是我找了很多最初的代码比如 v0.3.1 的我发现和本仓库的不太相同，我想来问一下 咱们这个 copy-rollup 是用了 rollup 第几版的代码呢 ？

**Comment by woai3c** [comment]
时间太久了，我印象中可能是 0.1.0 版本的代码，或者是 0.1.0-0.2.0 之间的代码

**Comment by xiaochengzi6** [comment]
感谢你的答复，我想我应该知道怎么做了，蟹蟹！！！

**Comment by woai3c** [comment]
> 感谢你的答复，我想我应该知道怎么做了，蟹蟹！！！

不客气 加油
